### PR TITLE
Refactored the library to support inline exceptions

### PR DESCRIPTION
**Pull request by mpscholten**
Implementation for #16

This PR splits the existing `ExceptionFactory` into two pieces: The first `MessageFactory` deals with creating the exception messages and the second (new) `ExceptionFactory` deals with creating the exception (e.g. using custom exception classes).

Because the new `MessageFactory` needs to be passed all the way down, the diff is very large (had to touch nearly all classes). Maybe we should introduce a `Config` class like `class Config { public $exceptionFactory; public $messageFactory; }` and pass this into the objects to avoid having to add new method parameters each time we add new configuration.

### CODE REVIEW

**Comment by mpscholten** [comment]
Could you take a quick look @yuvalherziger ? :) This pr allows to do `$this->param('email')->string()->email("Please provide a valid email")` to customize the error messages by the library.

**Comment by yuvalherziger** [comment]
Sure, will do

**Comment by yuvalherziger** [comment]
Excellent, really. 
Everything is crystal-clear and well structured. 
Now I guess a TOC in the README file is almost vital, given the growth of functionality :-)

**Comment by mpscholten** [comment]
Just opened #27 for that :) Good that you mentioned that again 👍

**Pull request merged**
