### PR TITLE
added gif and changed readme

### PR DESCRIPTION
**Pull request by yuvalherziger**
Gif will appear one merged, given that `https://github.com/mpscholten/request-parser/blob/master/images/autocomplete-anim.gif` is still not on the master branch

### CODE REVIEW

**Comment by yuvalherziger** [comment]
@mpscholten, you can preview it by changing the image URL in the markdown to `https://github.com/mpscholten/request-parser/blob/animated-gif/images/autocomplete-anim.gif`, just preview but don't save the changes 😄

**Comment by mpscholten** [comment]
Looks good :) Maybe we can keep the other screenshots though (maybe putting the static images below the gif)

**Comment by yuvalherziger** [comment]
Sure, that could work :)

**Comment by yuvalherziger** [comment]
And for the sake of good order, the gif portrays a capability that's yet to be merged (email PR) 😄

**Pull request merged**
